"""Constants for the Climaveneta iMXW and iLife2 integration."""

from datetime import timedelta

DOMAIN = "climaveneta"


DEFAULT_MODBUS_HUB = "/dev/ttyAMA0"
DEFAULT_SERIAL_SLAVE_ID = 1

CONF_HUB = "hub"
DEVICE_TYPE = "device_type"
CLIMAVENETA_IMXW = "imxw"
CLIMAVENETA_ILIFE2 = "ilife2"

TIMEOUT = 60

SCAN_INTERVAL = timedelta(seconds=90)


""" Climaveneta iMXW modbus registers"""
IMXW_ACTUAL_AIR_TEMPERATURE_REGISTER = 0x1002
IMXW_ACTUAL_WATER_TEMPERATURE_REGISTER = 0x1004

IMXW_STATE_READ_ON_OFF_REGISTER = 0x100F
IMXW_STATE_READ_FAN_ONLY_REGISTER = 0x1010
IMXW_STATE_READ_SEASON_REGISTER = 0x1013
IMXW_STATE_READ_FAN_AUTO_REGISTER = 0x1017
IMXW_STATE_READ_FAN_STOP_REGISTER = 0x1018
IMXW_STATE_READ_FAN_MIN_SPEED_REGISTER = 0x1019
IMXW_STATE_READ_FAN_MED_SPEED_REGISTER = 0x101A
IMXW_STATE_READ_FAN_MAX_SPEED_REGISTER = 0x101B
IMXW_STATE_READ_EV_WATER_REGISTER = 0x101C

IMXW_ALARM_T1_REGISTER = 0x1028
IMXW_ALARM_T3_REGISTER = 0x102A
IMXW_ALARM_WATER_DRAIN_REGISTER = 0x102B

IMXW_TARGET_TEMPERATURE_SUMMER_REGISTER = 0x102D
IMXW_TARGET_TEMPERATURE_WINTER_REGISTER = 0x102E

IMXW_STATE_WRITE_ON_OFF_REGISTER = 0x105C
IMXW_STATE_WRITE_MODE_REGISTER = 0x105D
IMXW_STATE_WRITE_FAN_SPEED_REGISTER = 0x105E

IMXW_AMBIENT_TEMP_EXTERNAL_PROBE_ENABLED_REGISTER = 0x1070
IMXW_AMBIENT_TEMP_EXTERNAL_PROBE_REGISTER = 0x1071

IMXW_MODE_SUMMER = 0
IMXW_MODE_WINTER = 1

IMXW_MODE_OFF = 0
IMXW_MODE_ON = 1


""" Climaveneta iLife modbus registers"""
ILIFE_ACTUAL_AIR_TEMPERATURE_REGISTER = 0
ILIFE_ACTUAL_WATER_TEMPERATURE_REGISTER = 1
ILIFE_STATE_READ_SETPOINT_REGISTER = 8
ILIFE_STATE_OUT_REGISTER = 9
ILIFE_STATE_READ_FAN_SPEED_REGISTER = 15
ILIFE_STATE_READ_REGISTER = 104
ILIFE_STATE_READ_ALARM_REGISTER = 105
ILIFE_STATE_READ_MODBUS_ADDRESS_REGISTER = 200
ILIFE_STATE_READ_PROGRAM_REGISTER = 201
ILIFE_MIN_WATER_TEMP_HEATING_REGISTER = 218
ILIFE_MAX_WATER_TEMP_COOLING_REGISTER = 219
ILIFE_TARGET_TEMPERATURE_REGISTER = 231
ILIFE_STATE_MAN_REGISTER = 233


ILIFE_WATER_BYPASS = 0
ILIFE_WATER_CIRCULATING = 1

""" global mode/flags"""
MODE_SUMMER = 0
MODE_WINTER = 1

MODE_OFF = 0
MODE_ON = 1

WATER_BYPASS = 0
WATER_CIRCULATING = 1

CLIMAVENETA_EXCHANGER_TEMPERATURE = "exchanger_temperature"
CLIMAVENETA_FAN_SPEED_RPM = "fan_speed_rpm"
CLIMAVENETA_MIN_WINTER = "min_voltage_winter"
CLIMAVENETA_MAX_WINTER = "max_voltage_winter"
CLIMAVENETA_MIN_SUMMER = "min_voltage_summer"
CLIMAVENETA_MAX_SUMMER = "max_voltage_summer"
CLIMAVENETA_PUMP_RELAY = "pump_relay_onoff"
CLIMAVENETA_ACTUAL_TEMPERATURE = "actual_temperature"
CLIMAVENETA_FIRMWARE_RELEASE = "firmware_release"
CLIMAVENETA_MAX_WATER_TEMP_SUMMER = "max_water_temp_summer"
CLIMAVENETA_MIN_WATER_TEMP_WINTER = "min_water_temp_winter"
CLIMAVENETA_MODBUS_ADDRESS = "modbus_address"
CLIMAVENETA_REAL_SETPOINT = "real_setpoint"
CLIMAVENETA_MOTOR_SPEED_SET = "motor_speed_set"
CLIMAVENETA_SETPOINT_HYSTERESIS = "setpoint_hysteresis"
CLIMAVENETA_DEAD_ZONE_CENTER = "dead_zone_center"
CLIMAVENETA_DEAD_ZONE_RANGE = "dead_zone_range"
CLIMAVENETA_T1_COMPENSATION_DELTA = "t1_compensation_delta"
CLIMAVENETA_ANTISTRAT_WAIT_TIME = "antistrat_wait_time"
CLIMAVENETA_T1_COMPENSATION_BASE_SUMMER = "t1_compensation_base_summer"
CLIMAVENETA_ANTISTRAT_TIME_SUMMER = "antistrat_time_summer"
CLIMAVENETA_T1_COMPENSATION_BASE_WINTER = "t1_compensation_base_winter"
CLIMAVENETA_ANTISTRAT_TIME_WINTER = "antistrat_time_winter"
CLIMAVENETA_OFFSET_NTC_ETN = "offset_ntc_etn"
CLIMAVENETA_T2_TEMPERATURE = "t2_temperature"
CLIMAVENETA_HVAC_STATUS = "hvac_status"

""" iMXW dip switch configuration (0x1005-0x1006) """
CLIMAVENETA_CONTINUOUS_VENTILATION = "continuous_ventilation"
CLIMAVENETA_MACHINE_SLAVE = "machine_slave"

""" iMXW diagnostic registers (0x1022-0x102B) """
CLIMAVENETA_RELAY5_FAN_HIGH = "relay5_fan_high"
CLIMAVENETA_WINDOW_INPUT = "window_input"
CLIMAVENETA_PUMP_ALARM_INPUT = "pump_alarm_input"
CLIMAVENETA_HEATER_PRESENT = "heater_present"
CLIMAVENETA_ANALOG_OUTPUT = "analog_output"
CLIMAVENETA_ALARM_T1 = "alarm_t1"
CLIMAVENETA_ALARM_T2 = "alarm_t2"
CLIMAVENETA_ALARM_T3 = "alarm_t3"
CLIMAVENETA_ALARM_WATER_DRAIN = "alarm_water_drain"

""" iLife2 alarm flag bits (register 105 ALR_STAT) """
CLIMAVENETA_ALARM_COM = "alarm_com"
CLIMAVENETA_ALARM_AIR = "alarm_air"
CLIMAVENETA_ALARM_H4 = "alarm_h4"
CLIMAVENETA_ALARM_ACQ_DAN = "alarm_acq_dan"
CLIMAVENETA_ALARM_H2 = "alarm_h2"
CLIMAVENETA_ALARM_H4_NID = "alarm_h4_nid"
CLIMAVENETA_ALARM_HI_RES = "alarm_hi_res"
CLIMAVENETA_ALARM_MOT = "alarm_mot"
CLIMAVENETA_ALARM_GRID = "alarm_grid"
CLIMAVENETA_ALARM_H2_NID = "alarm_h2_nid"
CLIMAVENETA_ALARM_FILTRO = "alarm_filtro"
CLIMAVENETA_ALARM_2AIR_M5 = "alarm_2air_m5"


